- name: Deploy CloudNativePG Helm Chart
  hosts: 192.168.3.129
  become: yes
  gather_facts: no
  vars:
    kubeconfig_path: /etc/rancher/rke2/rke2.yaml   # Update this path to your kubeconfig file

  tasks:
    - name: Ensure Helm is installed
      command: helm version
      register: helm_version
      failed_when: helm_version.rc != 0

    - name: Add CloudNativePG Helm repository
      kubernetes.core.helm:
        name: cnpg
        repo_url: https://cloudnative-pg.github.io/charts
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        release_namespace: cnpg-system

    - name: Update Helm repositories
      kubernetes.core.helm:
        name: cnpg
        repo_url: https://cloudnative-pg.github.io/charts
        state: present
        kubeconfig: "{{ kubeconfig_path }}"
        update_repos: yes
        release_namespace: cnpg-system

