- name: Deploy CloudNativePG Helm Chart
  hosts: 192.168.3.129
  become: yes
  gather_facts: no
  vars:
    kubeconfig_path: /etc/rancher/rke2/rke2.yaml   # Update this path to your kubeconfig file
    helm_chart: bitnami/chart-name  # Replace with your actual chart
    helm_release: my-release          # Replace with your release name
    helm_namespace: default          # Replace with your namespace if needed
    github_repo: https://raw.githubusercontent.com/Aminechouchene98/ansibleplaybooks/main/postgesql/values.yaml
    
  tasks:
    - name: Ensure Helm is installed
      command: helm version
      register: helm_version
      failed_when: helm_version.rc != 0

    - name: Download values.yaml from GitHub
      get_url:
        url: "{{ github_repo }}"
        dest: "/tmp/values.yaml"


