- name: Deploy CloudNativePG Helm Chart
  hosts: 192.168.3.129
  become: yes
  gather_facts: no
  vars:
    kubeconfig_path: /etc/rancher/rke2/rke2.yaml   # Update this path to your kubeconfig file
    helm_chart_ref: oci://registry-1.docker.io/bitnamicharts/postgresql-ha # Replace with your actual chart
    helm_release: my-release          # Replace with your release name
    helm_namespace: default          # Replace with your namespace if needed
    github_repo: https://raw.githubusercontent.com/Aminechouchene98/ansibleplaybooks/main/postgresql/values.yaml
    
  tasks:
    - name: Ensure Helm is installed
      command: helm version
      register: helm_version
      failed_when: helm_version.rc != 0

    - name: Download values.yaml from GitHub
      get_url:
        url: "{{ github_repo }}"
        dest: "/tmp/values.yaml"

    - name: Install Helm Chart
      kubernetes.core.helm:
        name: "{{ helm_release }}"
        chart_ref: "{{ helm_chart_ref }}"
        namespace: "{{ helm_namespace }}"
        values_files:
          - /tmp/values.yaml
        state: present
      register: helm_result
      
    - name: Display Helm result
      debug:
        msg: "{{ helm_result }}"  
